package com.konfigthis.client;

import com.konfigthis.client.api.AccessTokensApi;
import com.konfigthis.client.api.AccountMembersApi;
import com.konfigthis.client.api.AccountMembersBetaApi;
import com.konfigthis.client.api.AccountUsageBetaApi;
import com.konfigthis.client.api.ApplicationsBetaApi;
import com.konfigthis.client.api.ApprovalsApi;
import com.konfigthis.client.api.AuditLogApi;
import com.konfigthis.client.api.CodeReferencesApi;
import com.konfigthis.client.api.ContextSettingsApi;
import com.konfigthis.client.api.ContextsApi;
import com.konfigthis.client.api.CustomRolesApi;
import com.konfigthis.client.api.DataExportDestinationsApi;
import com.konfigthis.client.api.EnvironmentsApi;
import com.konfigthis.client.api.ExperimentsBetaApi;
import com.konfigthis.client.api.FeatureFlagsApi;
import com.konfigthis.client.api.FeatureFlagsBetaApi;
import com.konfigthis.client.api.FlagLinksBetaApi;
import com.konfigthis.client.api.FlagTriggersApi;
import com.konfigthis.client.api.FollowFlagsApi;
import com.konfigthis.client.api.InsightsChartsBetaApi;
import com.konfigthis.client.api.InsightsDeploymentsBetaApi;
import com.konfigthis.client.api.InsightsFlagEventsBetaApi;
import com.konfigthis.client.api.InsightsPullRequestsBetaApi;
import com.konfigthis.client.api.InsightsRepositoriesBetaApi;
import com.konfigthis.client.api.InsightsScoresBetaApi;
import com.konfigthis.client.api.IntegrationAuditLogSubscriptionsApi;
import com.konfigthis.client.api.IntegrationDeliveryConfigurationsBetaApi;
import com.konfigthis.client.api.IntegrationsBetaApi;
import com.konfigthis.client.api.MetricsApi;
import com.konfigthis.client.api.MetricsBetaApi;
import com.konfigthis.client.api.OAuth2ClientsApi;
import com.konfigthis.client.api.OtherApi;
import com.konfigthis.client.api.ProjectsApi;
import com.konfigthis.client.api.RelayProxyConfigurationsApi;
import com.konfigthis.client.api.ReleasePipelinesBetaApi;
import com.konfigthis.client.api.ReleasesBetaApi;
import com.konfigthis.client.api.ScheduledChangesApi;
import com.konfigthis.client.api.SegmentsApi;
import com.konfigthis.client.api.SegmentsBetaApi;
import com.konfigthis.client.api.TagsApi;
import com.konfigthis.client.api.TeamsApi;
import com.konfigthis.client.api.TeamsBetaApi;
import com.konfigthis.client.api.UserSettingsApi;
import com.konfigthis.client.api.UsersApi;
import com.konfigthis.client.api.UsersBetaApi;
import com.konfigthis.client.api.WebhooksApi;
import com.konfigthis.client.api.WorkflowTemplatesApi;
import com.konfigthis.client.api.WorkflowsApi;

public class LaunchDarkly {
    private ApiClient apiClient;
    public final AccessTokensApi accessTokens;
    public final AccountMembersApi accountMembers;
    public final AccountMembersBetaApi accountMembersBeta;
    public final AccountUsageBetaApi accountUsageBeta;
    public final ApplicationsBetaApi applicationsBeta;
    public final ApprovalsApi approvals;
    public final AuditLogApi auditLog;
    public final CodeReferencesApi codeReferences;
    public final ContextSettingsApi contextSettings;
    public final ContextsApi contexts;
    public final CustomRolesApi customRoles;
    public final DataExportDestinationsApi dataExportDestinations;
    public final EnvironmentsApi environments;
    public final ExperimentsBetaApi experimentsBeta;
    public final FeatureFlagsApi featureFlags;
    public final FeatureFlagsBetaApi featureFlagsBeta;
    public final FlagLinksBetaApi flagLinksBeta;
    public final FlagTriggersApi flagTriggers;
    public final FollowFlagsApi followFlags;
    public final InsightsChartsBetaApi insightsChartsBeta;
    public final InsightsDeploymentsBetaApi insightsDeploymentsBeta;
    public final InsightsFlagEventsBetaApi insightsFlagEventsBeta;
    public final InsightsPullRequestsBetaApi insightsPullRequestsBeta;
    public final InsightsRepositoriesBetaApi insightsRepositoriesBeta;
    public final InsightsScoresBetaApi insightsScoresBeta;
    public final IntegrationAuditLogSubscriptionsApi integrationAuditLogSubscriptions;
    public final IntegrationDeliveryConfigurationsBetaApi integrationDeliveryConfigurationsBeta;
    public final IntegrationsBetaApi integrationsBeta;
    public final MetricsApi metrics;
    public final MetricsBetaApi metricsBeta;
    public final OAuth2ClientsApi oAuth2Clients;
    public final OtherApi other;
    public final ProjectsApi projects;
    public final RelayProxyConfigurationsApi relayProxyConfigurations;
    public final ReleasePipelinesBetaApi releasePipelinesBeta;
    public final ReleasesBetaApi releasesBeta;
    public final ScheduledChangesApi scheduledChanges;
    public final SegmentsApi segments;
    public final SegmentsBetaApi segmentsBeta;
    public final TagsApi tags;
    public final TeamsApi teams;
    public final TeamsBetaApi teamsBeta;
    public final UserSettingsApi userSettings;
    public final UsersApi users;
    public final UsersBetaApi usersBeta;
    public final WebhooksApi webhooks;
    public final WorkflowTemplatesApi workflowTemplates;
    public final WorkflowsApi workflows;

    public LaunchDarkly() {
        this(null);
    }

    public LaunchDarkly(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.accessTokens = new AccessTokensApi(this.apiClient);
        this.accountMembers = new AccountMembersApi(this.apiClient);
        this.accountMembersBeta = new AccountMembersBetaApi(this.apiClient);
        this.accountUsageBeta = new AccountUsageBetaApi(this.apiClient);
        this.applicationsBeta = new ApplicationsBetaApi(this.apiClient);
        this.approvals = new ApprovalsApi(this.apiClient);
        this.auditLog = new AuditLogApi(this.apiClient);
        this.codeReferences = new CodeReferencesApi(this.apiClient);
        this.contextSettings = new ContextSettingsApi(this.apiClient);
        this.contexts = new ContextsApi(this.apiClient);
        this.customRoles = new CustomRolesApi(this.apiClient);
        this.dataExportDestinations = new DataExportDestinationsApi(this.apiClient);
        this.environments = new EnvironmentsApi(this.apiClient);
        this.experimentsBeta = new ExperimentsBetaApi(this.apiClient);
        this.featureFlags = new FeatureFlagsApi(this.apiClient);
        this.featureFlagsBeta = new FeatureFlagsBetaApi(this.apiClient);
        this.flagLinksBeta = new FlagLinksBetaApi(this.apiClient);
        this.flagTriggers = new FlagTriggersApi(this.apiClient);
        this.followFlags = new FollowFlagsApi(this.apiClient);
        this.insightsChartsBeta = new InsightsChartsBetaApi(this.apiClient);
        this.insightsDeploymentsBeta = new InsightsDeploymentsBetaApi(this.apiClient);
        this.insightsFlagEventsBeta = new InsightsFlagEventsBetaApi(this.apiClient);
        this.insightsPullRequestsBeta = new InsightsPullRequestsBetaApi(this.apiClient);
        this.insightsRepositoriesBeta = new InsightsRepositoriesBetaApi(this.apiClient);
        this.insightsScoresBeta = new InsightsScoresBetaApi(this.apiClient);
        this.integrationAuditLogSubscriptions = new IntegrationAuditLogSubscriptionsApi(this.apiClient);
        this.integrationDeliveryConfigurationsBeta = new IntegrationDeliveryConfigurationsBetaApi(this.apiClient);
        this.integrationsBeta = new IntegrationsBetaApi(this.apiClient);
        this.metrics = new MetricsApi(this.apiClient);
        this.metricsBeta = new MetricsBetaApi(this.apiClient);
        this.oAuth2Clients = new OAuth2ClientsApi(this.apiClient);
        this.other = new OtherApi(this.apiClient);
        this.projects = new ProjectsApi(this.apiClient);
        this.relayProxyConfigurations = new RelayProxyConfigurationsApi(this.apiClient);
        this.releasePipelinesBeta = new ReleasePipelinesBetaApi(this.apiClient);
        this.releasesBeta = new ReleasesBetaApi(this.apiClient);
        this.scheduledChanges = new ScheduledChangesApi(this.apiClient);
        this.segments = new SegmentsApi(this.apiClient);
        this.segmentsBeta = new SegmentsBetaApi(this.apiClient);
        this.tags = new TagsApi(this.apiClient);
        this.teams = new TeamsApi(this.apiClient);
        this.teamsBeta = new TeamsBetaApi(this.apiClient);
        this.userSettings = new UserSettingsApi(this.apiClient);
        this.users = new UsersApi(this.apiClient);
        this.usersBeta = new UsersBetaApi(this.apiClient);
        this.webhooks = new WebhooksApi(this.apiClient);
        this.workflowTemplates = new WorkflowTemplatesApi(this.apiClient);
        this.workflows = new WorkflowsApi(this.apiClient);
    }

}
